### PR TITLE
Update readable-stream to faster major release.

### PR DESCRIPTION
**Pull request by paulmillr**
@iarna could you spin off a release with this please. I've tested the change.

### CODE REVIEW

**Comment by paulmillr** [comment]
@iarna still needs a NPM releaes

**Comment by iarna** [comment]
@paulmillr I'm aware. It'll happen when it happens.

**Comment by iarna** [comment]
@paulmillr Did you mean in _npm_ itself? Because it will get in eventually, but there's no impact one way or the other, as npm doesn't use any of the stream related code paths in this module. ¯\_(ツ)_/¯

**Comment by paulmillr** [comment]
Thanks anyway!

**Pull request closed without merging**
